version: '3.8'

services:
  db:
    image: postgres:15.5
    container_name: todo-db
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_todo:/var/lib/postgresql/data

volumes:
  postgres_data_todo:
