spring:
  application:
    name: spring-boot-todo
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers_skip_column_definitions: 'true'
        globally_quoted_identifiers: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    username: todo
    url: jdbc:postgresql://localhost:5432/todo
    password: todo
